version: '3.3'

services:

  identity_db:
    image: postgres:alpine3.15
    container_name: identity_db
    ports:
      - "5442:5432"
      # 127.0.0.1:

    environment:
      - POSTGRES_DB=identity_database
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root123
    restart: unless-stopped
    volumes:
      - identity_db_data:/var/lib/postgresql/data
    networks:
      - net_flight
  
  flight_db:
    image: postgres:alpine3.15
    container_name: flight_db
    ports:
      - "5443:5432"
      # 127.0.0.1:
    environment:
      - POSTGRES_DB=flight_database
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root123
    restart: unless-stopped
    volumes:
      - flight_db_data:/var/lib/postgresql/data
    networks:
      - net_flight
  
  analysis_db:
    image: postgres:alpine3.15
    container_name: analysis_db
    ports:
      - "5444:5432"
      # 127.0.0.1:
    environment:
      - POSTGRES_DB=analysis_database
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root123
    restart: unless-stopped
    volumes:
      - analysis_db_data:/var/lib/postgresql/data
    networks:
      - net_flight

  identity_service:
    # build: ./identity_service
    image: cloudproject_identity_service:latest
    ports:
      - 8004:8000
    environment:
      - DEPLOY_DOCKER=true
      - JWT_SIGNING_KEY=key123
      - POSTGRES_DB=identity_database
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root123
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=identity_db
    networks:
      - net_flight
    depends_on:
      - identity_db
    deploy:
      mode: global
      placement:
        constraints: [node.hostname == docker-desktop]

  flight_service:
    # build: ./flight_service
    image: cloudproject_flight_service:latest
    ports:
      - 8001:8000
    environment:
      - DEPLOY_DOCKER=true
      - JWT_SIGNING_KEY=key123
      - POSTGRES_DB=flight_database
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root123
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=flight_db
    networks:
      - net_flight
    depends_on:
      - flight_db

  analysis_service:
    # build: ./analysis_service
    image: cloudproject_analysis_service:latest
    ports:
      - 8002:8000
    environment:
      - DEPLOY_DOCKER=true
      - JWT_SIGNING_KEY=key123
      - POSTGRES_DB=analysis_database
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root123
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=analysis_db
      - FLIGHT_POSTGRES_DB=flight_database
      - FLIGHT_POSTGRES_USER=postgres
      - FLIGHT_POSTGRES_PASSWORD=root123
      - FLIGHT_POSTGRES_PORT=5432
      - FLIGHT_POSTGRES_HOST=flight_db
    networks:
      - net_flight
    depends_on:
      - flight_db
      - flight_service
      - analysis_db

networks:
  net_flight:

volumes:
  identity_db_data:
  flight_db_data:
  analysis_db_data:
