# Generated by Django 3.2 on 2022-04-06 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservePlane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=128)),
                ('plane_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserves', to='planes.planetype')),
            ],
        ),
    ]
