# Generated by Django 3.2 on 2022-04-20 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0002_reserveplane'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserveplane',
            name='plane_type',
        ),
        migrations.AddField(
            model_name='reserveplane',
            name='flight',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reserves', to='planes.flight'),
        ),
    ]
